### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by mpilka** [rejuce/LikeTaskManager#1] opened 2020-06-18 08:38 UTC
* Ubuntu 18.04.4 LTS
```
$ ./LikeTaskManager-x86_64.AppImage
ERROR: opening handler for device wlp4s0: Operation not permitted
Nethogs Processing Loop FAILURE
cpu stat reader started
ram stat reader started
disk stat reader started
network stat reader started
network stat reader started
Floating point exception (core dumped)

$ sudo ./LikeTaskManager-x86_64.AppImage 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Ethernet link detected
cpu stat reader started
ram stat reader started
disk stat reader started
Floating point exception
```

**Comment by rejuce** [comment] 2020-06-18 16:57
@mpilka thank you for the issue. May I ask about your system configuration? How many disks? What kind of disks are present in your system? I will investigate where that might come from

**Comment by rejuce** [comment] 2020-06-21 19:34
@mpilka v2.1 is now online, would you kindly update to that version, try again and if it is not working send me the console output? I also wonder, did the exception occur right on start or later?

**Comment by mpilka** [comment] 2020-06-22 11:40
Hello,
behaviour is identical with new version, following error occurs during startup:

$ ./LikeTaskManager-x86_64.AppImage 
ERROR: opening handler for device wlp4s0: Operation not permitted
Nethogs Processing Loop FAILURE
cpu stat reader started
ram stat reader started
disk stat reader started
network stat reader started
process stat reader started
Floating point exception (core dumped)

 ✘  Downloads  $ sudo ./LikeTaskManager-x86_64.AppImage 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Ethernet link detected
cpu stat reader started
ram stat reader started
disk stat reader started
network stat reader started
process stat reader started
Floating point exception

 ✘  Downloads  $ md5sum ./LikeTaskManager-x86_64.AppImage 
7d65fcdbcb910f29338e0790e947fcca  ./LikeTaskManager-x86_64.AppImage

,Thanks,
Martin

**Comment by rejuce** [comment] 2020-06-27 21:10
@mpilka  thank you for your feedback, by that i learned that the problem does not seem to happen on the data acquisition side.
I am still a bit in the dark though, as I cant reproduce the error on any of the test systems.

I added a new release, which contains some code cleanup and additional exception handling to narrow it down further. I kindly ask you to update, try and send me the output again.

https://github.com/rejuce/LikeTaskManager/releases/tag/2.2

**Comment by mpilka** [comment] 2020-06-29 12:13
Same behaviour, unfortunately:
```
$ md5sum LikeTaskManager-x86_64.AppImage 
434334e92e242277aaaba04db973e3b8  LikeTaskManager-x86_64.AppImage

$ ./LikeTaskManager-x86_64.AppImage
ERROR: opening handler for device wlp4s0: Operation not permitted
Nethogs Processing Loop FAILURE
cpu stat reader started
ram stat reader started
disk stat reader started
network stat reader started
process stat reader started
Floating point exception (core dumped)

$ sudo ./LikeTaskManager-x86_64.AppImage
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Ethernet link detected
cpu stat reader started
ram stat reader started
disk stat reader started
network stat reader started
Floating point exception
```

I am afraid progress is possible only with debug support (something like `./LikeTaskManager-x86_64.AppImage --debug`).

Thanks,
Martin

**Comment by jnezbeda** [comment] 2020-07-01 11:45
Hi @rejuce I have same experience like @mpilka. There is my output on Lubuntu 20.04 LTS:

$ ./'LikeTaskManager-x86_64(1).AppImage'
ERROR: opening handler for device enp4s0: Operation not permitted
Nethogs Processing Loop FAILURE
cpu stat reader started
ram stat reader started
disk stat reader started
network stat reader started
process stat reader started
Floating point exception (SIGFPE) (core dumped [memory image saved])

sudo ./'LikeTaskManager-x86_64(1).AppImage'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Ethernet link detected
cpu stat reader started
ram stat reader started
disk stat reader started
network stat reader started
process stat reader started
Floating point exception (SIGFPE)

I tried v2.2 and also old one.

**Comment by rejuce** [comment] 2020-07-01 12:30
thank you for the feedback.
@mpilka , @jnezbeda  can you please send me the output of 
sudo lshw ?

**Comment by jnezbeda** [comment] 2020-07-01 12:57
yes I will send it, do you fill email address in your profile? I would like to send it there. Not publicly. Thx

**Comment by rejuce** [comment] 2020-07-01 13:01
@jnezbeda thank you for your help, understand, now set

**Comment by mpilka** [comment] 2020-07-01 13:45
[lshw.txt](https://github.com/rejuce/LikeTaskManager/files/4858223/lshw.txt)

**Comment by rejuce** [comment] 2020-07-03 21:25
@mpilka ,  @jnezbeda   if somebody of you two has time please find v2.2.1. I did not find anything weird in your lshw files
unfortunately I still did not manage to reproduce the behaviour on any machine which makes it even harder to find the root of the problem.

I can see that my main window is instantiated and none of the data aqusitions threads throws the floating point exeption. the slots where the data is processed are all wrapped in cache(...), also no exeption is coming from there.

By now I have the suspicion that the exception comes from a Qt plugin, or Qt code that loads the user interface. I found several threads regarding that having to do with an outdated opencl on the system. as the app image should be rather independant on the system I might have smt wrong in the bundling.

I added more verbosity to the launch of the application again. If nothing is changed 
please set the environment variabel  in ther console 
export QT_DEBUG_PLUGINS=1

before starting the app
./LikeTaskManager....

there should be then A LOT of output text from Qt itself. Please send me that

**Comment by jnezbeda** [comment] 2020-07-15 08:48
Hi @rejuce sry for w8 (holiday...). Same problem with v2.2.1. Output files are attached bellow.


$ ./'LikeTaskManager-x86_64(2).AppImage' 
setting auto DPI screen scale factor
instantiating QApplication
instantiating MainWindow
ERROR: opening handler for device enp4s0: operation not permitted
Nethogs Processing Loop FAILURE
cpu stat reader started
ram stat reader started
disk stat reader started
network stat reader started
process stat reader started
assembling the left ItemWidget with currently present devices
Floating point exception (SIGFPE) (core dumped [memory image saved])

sudo !!
sudo ./'LikeTaskManager-x86_64(2).AppImage' 
setting auto DPI screen scale factor
instantiating QApplication
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
instantiating MainWindow
Ethernet link detected
cpu stat reader started
ram stat reader started
disk stat reader started
network stat reader started
process stat reader started
assembling the left ItemWidget with currently present devices
Floating point exception (SIGFPE)


**export QT_DEBUG_PLUGINS=1**

$ ./'LikeTaskManager-x86_64(2).AppImage' >> **no_sudo.txt** 2>&1
Floating point exception (SIGFPE) (core dumped [memory image saved])

sudo ./'LikeTaskManager-x86_64(2).AppImage' >> **sudo.txt** 2>&1
Floating point exception (SIGFPE)

[no_sudo.txt](https://github.com/rejuce/LikeTaskManager/files/4923994/no_sudo.txt)
[sudo.txt](https://github.com/rejuce/LikeTaskManager/files/4923997/sudo.txt)

**Comment by rejuce** [comment] 2020-07-15 10:43
@ jnezbeda  thank you for the output. certainly one step further. I will update once I could atempt a fix

**Comment by rejuce** [comment] 2020-07-17 20:31
@mpilka , @jnezbeda can you please update to v 2.2.2 and see if the floating point issue is resolved?

**Comment by jnezbeda** [comment] 2020-07-18 08:13
@rejuce : sry, but with v2.2.2 is the same problem.

I also tried different HW (laptop) and different OS (live cd):

_[liveuser@localhost-live Downloads]$ ./LikeTaskManager-x86_64.AppImage 
setting auto DPI screen scale factor
instantiating QApplication
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
instantiating MainWindow
ERROR: opening handler for device wlp2s0: Operation not permitted
Nethogs Processing Loop FAILURE
cpu stat reader started
ram stat reader started
disk stat reader started
network stat reader started
process stat reader started
assembling the left ItemWidget with currently present devices
Floating point exception (core dumped)_

_sudo ./LikeTaskManager-x86_64.AppImage 
setting auto DPI screen scale factor
instantiating QApplication
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
instantiating MainWindow
Ethernet link detected
cpu stat reader started
ram stat reader started
disk stat reader started
network stat reader started
process stat reader started
assembling the left ItemWidget with currently present devices
Floating point exception_

short from neofetch:
_Fedora 32 (Thirty Two) x86_64 
Kernel: 5.6.6-300.fc32.x86_64 
CPU: Intel i5-6300U (4) @ 3.000GHz 
GPU: Intel Skylake GT2 [HD Graphics 520] 
Memory: 1693MiB / 7838MiB_

**Comment by rejuce** [comment] 2020-07-19 04:49
@jnezbeda ah thank you for the feedback, what a tricky bug... i finally found another system where I could reporudce it and poke into it a bit more. the next realse will fix it ;)

**Comment by rejuce** [comment] 2020-07-19 20:15
@jnezbeda , @mpilka  I assume both your systems did not have any swap memory configured? It seems that I did not fully account for that possibility causing the issue. Please find v2.3 now finally resolving that

**Comment by jnezbeda** [comment] 2020-07-20 05:31
@rejuce : great, that was it! cya

**Closed** 2020-07-20 07:55 UTC
Labels: question
